In [14]:
import pandas as pd
import glob

In [15]:
files = glob.glob('data/processed_weather/varginha/*.csv')

dfs = []

for file in files:
    df = pd.read_csv(file)
    dfs.append(df)

df_weather = pd.concat(dfs, ignore_index=True)
df_weather

        datetime  chuva       temp  temp_max  temp_min    umidade
0     2016-01-01    5.2  22.370833      30.3      18.6  81.333333
1     2016-01-02   17.0  21.904167      28.6      19.0  85.000000
2     2016-01-03   40.8  21.741667      27.7      19.4  87.000000
3     2016-01-04    1.4  21.162500      26.1      17.4  79.416667
4     2016-01-05    0.0  22.075000      28.4      17.7  65.583333
...          ...    ...        ...       ...       ...        ...
2552  2017-12-27    0.0  22.735000      32.1      18.3  75.700000
2553  2017-12-28   20.8  20.950000      29.5      18.3  86.375000
2554  2017-12-29    0.0  24.880000      27.8      20.5  66.600000
2555  2017-12-30   22.6  19.700000      23.4      17.2  88.823529
2556  2017-12-31   12.6  20.041176      22.5      17.7  87.529412

[2557 rows x 6 columns]

In [16]:
df_weather['datetime'] = pd.to_datetime(df_weather['datetime'])
df_weather = df_weather.sort_values('datetime')

df_weather = df_weather.drop_duplicates(subset='datetime')

df_weather.to_csv("data/weather.csv", index=False)
df_weather

       datetime  chuva       temp  temp_max  temp_min    umidade
1826 2012-01-01   27.2  20.016667      22.7      19.1  95.833333
1827 2012-01-02   22.6  19.829167      23.9      17.8  92.916667
1828 2012-01-03    0.4  21.462500      28.2      17.5  79.666667
1829 2012-01-04    0.0  22.187500      29.3      15.9  67.416667
1830 2012-01-05    0.0  22.341667      29.5      15.5  66.708333
...         ...    ...        ...       ...       ...        ...
1091 2018-12-27   15.8  19.958333      22.5      17.4  91.000000
1092 2018-12-28    0.4  21.895833      29.0      18.4  79.125000
1093 2018-12-29    1.0  22.166667      29.2      17.3  76.458333
1094 2018-12-30    0.0  23.741667      30.7      18.4  71.875000
1095 2018-12-31    0.0  24.295652      30.0      19.2  68.869565

[2557 rows x 6 columns]