# LSTM Coffee Price

# 1. Ambient preparation

In [1]:
from IPython.display import display, HTML

display(HTML("<style>.container {widht: 100% !important;}</style>"))

## 1.1. Import packages

In [2]:
import subprocess
import sys
import os
import yfinance
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

import torch

## 1.2. GPU check

In [3]:
if torch.cuda.is_available():
    print("__CUDNN VERSION:", torch.backends.cudnn.version())
    print("Device Name:", torch.cuda.get_device_name(0))
    device = 'cuda'
else:
    print("CUDA is not available.")
    device = 'cpu'

print('Device:', device)

__CUDNN VERSION: 91900
Device Name: NVIDIA GeForce RTX 5070
Device: cuda

# 2. Dataset

In [12]:
coffee = yf.download("KC=F", start="2005-01-01", end="2026-04-01", interval="1d")
dollar = yf.download("BRL=X", start="2005-01-01", end="2026-04-01", interval="1d")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
coffee.head()

Price            Close        High         Low   Open Volume
Ticker            KC=F        KC=F        KC=F   KC=F   KC=F
Date
2005-01-03  103.099998  105.099998  102.500000  103.5  12032
2005-01-04  101.449997  102.500000   99.800003  101.5  14840
2005-01-05   98.500000  104.750000   98.000000  101.0  16983
2005-01-06   96.800003   99.000000   95.599998   98.0   8470
2005-01-07   96.250000   98.650002   96.099998   97.0   8380

In [14]:
dollar.head()

Price        Close    High     Low    Open Volume
Ticker       BRL=X   BRL=X   BRL=X   BRL=X  BRL=X
Date
2006-03-24  2.1547  2.1665  2.1541  2.1665      0
2006-03-27  2.1503  2.1558  2.1503  2.1555      0
2006-03-28  2.1677  2.1690  2.1677  2.1682      0
2006-03-29  2.2206  2.2280  2.2206  2.2270      0
2006-03-30  2.1922  2.2117  2.1867  2.2117      0