# LSTM Coffee Price

# 1. Ambient preparation

In [1]:
from IPython.display import display, HTML

display(HTML("<style>.container {widht: 100% !important;}</style>"))

## 1.1. Import packages

In [2]:
import subprocess
import sys
import os
import yfinance
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

import torch

## 1.2. GPU check

In [3]:
if torch.cuda.is_available():
    print("__CUDNN VERSION:", torch.backends.cudnn.version())
    print("Device Name:", torch.cuda.get_device_name(0))
    device = 'cuda'
else:
    print("CUDA is not available.")
    device = 'cpu'

print('Device:', device)

__CUDNN VERSION: 91900
Device Name: NVIDIA GeForce RTX 5070
Device: cuda

# 2. Dataset

In [5]:
coffee = yf.download("KC=F")
dollar = yf.download("BRL=X")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [6]:
coffee.head()

Price            Close        High         Low        Open Volume
Ticker            KC=F        KC=F        KC=F        KC=F   KC=F
Date
2026-03-27  301.700012  309.100006  300.000000  307.399994  13302
2026-03-30  292.549988  301.000000  291.649994  300.500000  15119
2026-03-31  298.350006  299.000000  292.799988  294.399994  15229
2026-04-01  297.799988  300.750000  291.049988  298.000000  18200
2026-04-02  295.399994  301.500000  292.250000  300.850006  13705

In [7]:
dollar.head()

Price        Close    High       Low      Open Volume
Ticker       BRL=X   BRL=X     BRL=X     BRL=X  BRL=X
Date
2026-03-27  5.2351  5.2752  5.211410  5.231225      0
2026-03-30  5.2380  5.2703  5.218984  5.237900      0
2026-03-31  5.2640  5.2648  5.202400  5.263700      0
2026-04-01  5.1928  5.2021  5.148194  5.192100      0
2026-04-02  5.1545  5.1870  5.143000  5.154600      0